# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cvs2E6oRshHnj7h7eTGVpcgjH6f7tppH
"""

import random

STYLE={
    "genre":"Khmer epic romantic ballad",
    "mood":"Cinematic emotional"
}

PAT=[
    ["D","","U",""],
    ["D","g","U",""],
    ["D","g","D","U"],
    ["D","a","D","U"]
]

def perf(e):
    bar=[]
    for i,s in enumerate(random.choice(PAT)):
        if s=="":
            bar.append(f"B{i+1}:rest")
            continue
        vel=random.randint(60,80)+e+(15 if s=="a" else 0)
        t=round(random.uniform(-0.02,0.025),3)
        art="Slide" if e>15 and random.random()>0.6 else "Normal"
        bar.append(f"B{i+1}:{'Ghost' if s=='g' else 'Hit'},V{vel},T{t},{art}")
    return bar

MIX={
    "EQ":"HPF 40Hz, bass boost 90Hz, cut 300Hz",
    "COMP":"Ratio 3:1, fast attack, medium release",
    "SAT":"Soft analog",
    "STEREO":"Bass mono, guitar wide"
}

MASTER={
    "EQ":"Low clean, high air",
    "COMP":"Glue 2:1",
    "LIMIT":"-0.9dB, loud"
}

def build():
    print("STYLE:",STYLE)
    print("MIX:",MIX)
    print("MASTER:",MASTER)
    for sec,e in [("Intro",6),("Verse",10),("Chorus",22),("Outro",8)]:
        print("\n",sec)
        for b in range(1,5):
            print("Bar",b,perf(e))

build()